name: publish-tools
on:
  workflow_run:
    workflows: [publish-base]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the cuda11.8.0-ubuntu22.04-pytorch-conda-tools Docker image
        run: |
          docker build cuda11.8.0-ubuntu22.04-pytorch-conda-tools --tag ghcr.io/viwainvestgmbh/runpod-llm-cuda118-pytorch-tools:latest
          docker push ghcr.io/viwainvestgmbh/runpod-llm-cuda118-pytorch-tools:latest
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering publish-tools failed'
