name: publish-base
on:
  push:
    paths:
      - 'cuda11.8.0-ubuntu22.04-pytorch-conda-base/**'
jobs:
  publish-cuda118-ubuntu2204-pytorch-conda-base-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the cuda118-ubuntu2204-pytorch-conda-base Docker image
        run: |
          docker build cuda11.8.0-ubuntu22.04-pytorch-conda-base --tag ghcr.io/viwainvestgmbh/cuda11.8.0-ubuntu22.04-pytorch-conda-base:latest
          docker push ghcr.io/viwainvestgmbh/cuda11.8.0-ubuntu22.04-pytorch-conda-base:latest
